_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
dataset:
    value: MNIST
epochs:
    value: 10
learning_rate:
    value: 0.05
model:
    value: CNN
